import { withPayload } from '@payloadcms/next/withPayload'
import createNextIntlPlugin from 'next-intl/plugin'

const withNextIntl = createNextIntlPlugin('./src/i18n/request.ts')

// Workers build: Payload is excluded (see scripts/cf-prebuild.mjs) and `standalone`
// is a Node-server output the adapter has no use for. Docker path is unaffected.
const isCloudflare = process.env.CF_BUILD === '1'

/** @type {import('next').NextConfig} */
const nextConfig = {
  output: isCloudflare ? undefined : 'standalone',
  poweredByHeader: false,
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'trident-software.ch', pathname: '/wp-content/uploads/**' },
    ],
  },

  async redirects() {
    return [
      // ─── Static page redirects (old WordPress URLs → new Next.js URLs) ───
      { source: '/about-us', destination: '/about', permanent: true },
      { source: '/about-us/', destination: '/about', permanent: true },
      { source: '/our-team', destination: '/team', permanent: true },
      { source: '/our-team/', destination: '/team', permanent: true },
      { source: '/contacts', destination: '/contact', permanent: true },
      { source: '/contacts/', destination: '/contact', permanent: true },
      { source: '/our-solutions', destination: '/solutions', permanent: true },
      { source: '/our-solutions/', destination: '/solutions', permanent: true },
      { source: '/our-solutions/websites', destination: '/solutions/websites', permanent: true },
      { source: '/our-solutions/websites/', destination: '/solutions/websites', permanent: true },
      { source: '/our-solutions/websites/online-boutique', destination: '/solutions/websites/online-boutique', permanent: true },
      { source: '/our-solutions/websites/online-boutique/', destination: '/solutions/websites/online-boutique', permanent: true },
      { source: '/our-solutions/websites/web-brochure', destination: '/solutions/websites/web-brochure', permanent: true },
      { source: '/our-solutions/websites/web-brochure/', destination: '/solutions/websites/web-brochure', permanent: true },
      { source: '/our-solutions/websites/user-portal', destination: '/solutions/websites/user-portal', permanent: true },
      { source: '/our-solutions/websites/user-portal/', destination: '/solutions/websites/user-portal', permanent: true },
      { source: '/our-solutions/websites/sme-website', destination: '/solutions/websites/sme-website', permanent: true },
      { source: '/our-solutions/websites/sme-website/', destination: '/solutions/websites/sme-website', permanent: true },
      { source: '/our-solutions/e-commerce', destination: '/solutions/e-commerce', permanent: true },
      { source: '/our-solutions/e-commerce/', destination: '/solutions/e-commerce', permanent: true },
      { source: '/site-price', destination: '/pricing', permanent: true },
      { source: '/site-price/', destination: '/pricing', permanent: true },
      { source: '/services/startups-cto-service', destination: '/services/cto-as-a-service', permanent: true },
      { source: '/services/startups-cto-service/', destination: '/services/cto-as-a-service', permanent: true },
      { source: '/services/software-development', destination: '/services/software-engineering', permanent: true },
      { source: '/services/software-development/', destination: '/services/software-engineering', permanent: true },
      { source: '/8move', destination: '/products', permanent: true },
      { source: '/8move/', destination: '/products', permanent: true },
      { source: '/iam-trade', destination: '/products/iam-trade', permanent: true },
      { source: '/iam-trade/', destination: '/products/iam-trade', permanent: true },

      // ─── EN blog posts: root level → /blog/ ───────────────────────────────
      { source: '/from-traditional-to-flexible-wms-mobile-app', destination: '/blog/from-traditional-to-flexible-wms-mobile-app', permanent: true },
      { source: '/from-traditional-to-flexible-wms-mobile-app/', destination: '/blog/from-traditional-to-flexible-wms-mobile-app', permanent: true },
      { source: '/free-advertising-for-restaurants-through-customer-feedback', destination: '/blog/free-advertising-for-restaurants-through-customer-feedback', permanent: true },
      { source: '/free-advertising-for-restaurants-through-customer-feedback/', destination: '/blog/free-advertising-for-restaurants-through-customer-feedback', permanent: true },
      { source: '/simplifying-your-search-how-iam-trade-makes-finding-products-easy', destination: '/blog/simplifying-your-search-how-iam-trade-makes-finding-products-easy', permanent: true },
      { source: '/simplifying-your-search-how-iam-trade-makes-finding-products-easy/', destination: '/blog/simplifying-your-search-how-iam-trade-makes-finding-products-easy', permanent: true },
      { source: '/driving-growth-essential-tactics-for-your-ecommerce-business', destination: '/blog/driving-growth-essential-tactics-for-your-ecommerce-business', permanent: true },
      { source: '/driving-growth-essential-tactics-for-your-ecommerce-business/', destination: '/blog/driving-growth-essential-tactics-for-your-ecommerce-business', permanent: true },
      { source: '/the-power-of-outsourcing-unlocking-efficiency-and-innovation-in-short-term-projects', destination: '/blog/the-power-of-outsourcing-unlocking-efficiency-and-innovation-in-short-term-projects', permanent: true },
      { source: '/the-power-of-outsourcing-unlocking-efficiency-and-innovation-in-short-term-projects/', destination: '/blog/the-power-of-outsourcing-unlocking-efficiency-and-innovation-in-short-term-projects', permanent: true },
      { source: '/nft-in-game-trading-platforms', destination: '/blog/nft-in-game-trading-platforms', permanent: true },
      { source: '/nft-in-game-trading-platforms/', destination: '/blog/nft-in-game-trading-platforms', permanent: true },
      { source: '/arenawave-digital-court-system', destination: '/blog/arenawave-digital-court-system', permanent: true },
      { source: '/arenawave-digital-court-system/', destination: '/blog/arenawave-digital-court-system', permanent: true },
      { source: '/iot-blockchain-can-it-truly-deliver', destination: '/blog/iot-blockchain-can-it-truly-deliver', permanent: true },
      { source: '/iot-blockchain-can-it-truly-deliver/', destination: '/blog/iot-blockchain-can-it-truly-deliver', permanent: true },
      { source: '/strengthening-small-and-medium-sized-businesses-through-advanced-security-solutions', destination: '/blog/strengthening-small-and-medium-sized-businesses-through-advanced-security-solutions', permanent: true },
      { source: '/strengthening-small-and-medium-sized-businesses-through-advanced-security-solutions/', destination: '/blog/strengthening-small-and-medium-sized-businesses-through-advanced-security-solutions', permanent: true },
      { source: '/secure-your-cloud-on-a-budget-a-guide-for-smbs', destination: '/blog/secure-your-cloud-on-a-budget-a-guide-for-smbs', permanent: true },
      { source: '/secure-your-cloud-on-a-budget-a-guide-for-smbs/', destination: '/blog/secure-your-cloud-on-a-budget-a-guide-for-smbs', permanent: true },
      { source: '/presenting-zenit-auto-our-new-b2b-auto-parts-platform', destination: '/blog/presenting-zenit-auto-our-new-b2b-auto-parts-platform', permanent: true },
      { source: '/presenting-zenit-auto-our-new-b2b-auto-parts-platform/', destination: '/blog/presenting-zenit-auto-our-new-b2b-auto-parts-platform', permanent: true },
      { source: '/trident-softwares-venture-evolution-it-package-empowers-startups-insights-from-foire-du-valais-2024', destination: '/blog/trident-softwares-venture-evolution-it-package-empowers-startups-insights-from-foire-du-valais-2024', permanent: true },
      { source: '/trident-softwares-venture-evolution-it-package-empowers-startups-insights-from-foire-du-valais-2024/', destination: '/blog/trident-softwares-venture-evolution-it-package-empowers-startups-insights-from-foire-du-valais-2024', permanent: true },
      { source: '/introducing-our-new-b2b-client-management-panel', destination: '/blog/introducing-our-new-b2b-client-management-panel', permanent: true },
      { source: '/introducing-our-new-b2b-client-management-panel/', destination: '/blog/introducing-our-new-b2b-client-management-panel', permanent: true },

      // ─── FR localized page redirects ──────────────────────────────────────
      { source: '/fr/a-propos-de-nous', destination: '/about', permanent: true },
      { source: '/fr/a-propos-de-nous/', destination: '/about', permanent: true },
      { source: '/fr/notre-equipe', destination: '/team', permanent: true },
      { source: '/fr/notre-equipe/', destination: '/team', permanent: true },
      { source: '/fr/contacts', destination: '/contact', permanent: true },
      { source: '/fr/contacts/', destination: '/contact', permanent: true },
      { source: '/fr/nos-services', destination: '/services', permanent: true },
      { source: '/fr/nos-services/', destination: '/services', permanent: true },
      { source: '/fr/nos-services/conseil-en-cloud', destination: '/services/cloud-consulting', permanent: true },
      { source: '/fr/nos-services/conseil-en-cloud/', destination: '/services/cloud-consulting', permanent: true },
      { source: '/fr/nos-services/embarque-et-iot', destination: '/services/embedded-and-iot', permanent: true },
      { source: '/fr/nos-services/embarque-et-iot/', destination: '/services/embedded-and-iot', permanent: true },
      { source: '/fr/nos-services/startups-cto-as-a-service', destination: '/services/cto-as-a-service', permanent: true },
      { source: '/fr/nos-services/startups-cto-as-a-service/', destination: '/services/cto-as-a-service', permanent: true },
      { source: '/fr/nos-services/ingenierie-logicielle', destination: '/services/software-engineering', permanent: true },
      { source: '/fr/nos-services/ingenierie-logicielle/', destination: '/services/software-engineering', permanent: true },
      { source: '/fr/nos-services/developpement-de-logiciels', destination: '/services/software-engineering', permanent: true },
      { source: '/fr/nos-services/developpement-de-logiciels/', destination: '/services/software-engineering', permanent: true },
      { source: '/fr/nos-services/services-dia', destination: '/services/ai-services', permanent: true },
      { source: '/fr/nos-services/services-dia/', destination: '/services/ai-services', permanent: true },
      { source: '/fr/nos-solutions', destination: '/solutions', permanent: true },
      { source: '/fr/nos-solutions/', destination: '/solutions', permanent: true },
      { source: '/fr/nos-solutions/sites-web', destination: '/solutions/websites', permanent: true },
      { source: '/fr/nos-solutions/sites-web/', destination: '/solutions/websites', permanent: true },
      { source: '/fr/nos-solutions/sites-web/boutique-en-ligne', destination: '/solutions/websites/online-boutique', permanent: true },
      { source: '/fr/nos-solutions/sites-web/boutique-en-ligne/', destination: '/solutions/websites/online-boutique', permanent: true },
      { source: '/fr/nos-solutions/sites-web/brochure-web', destination: '/solutions/websites/web-brochure', permanent: true },
      { source: '/fr/nos-solutions/sites-web/brochure-web/', destination: '/solutions/websites/web-brochure', permanent: true },
      { source: '/fr/nos-solutions/sites-web/portail-utilisateur', destination: '/solutions/websites/user-portal', permanent: true },
      { source: '/fr/nos-solutions/sites-web/portail-utilisateur/', destination: '/solutions/websites/user-portal', permanent: true },
      { source: '/fr/nos-solutions/sites-web/site-web-pme', destination: '/solutions/websites/sme-website', permanent: true },
      { source: '/fr/nos-solutions/sites-web/site-web-pme/', destination: '/solutions/websites/sme-website', permanent: true },
      { source: '/fr/nos-solutions/e-commerce', destination: '/solutions/e-commerce', permanent: true },
      { source: '/fr/nos-solutions/e-commerce/', destination: '/solutions/e-commerce', permanent: true },
      { source: '/fr/site-prix', destination: '/pricing', permanent: true },
      { source: '/fr/site-prix/', destination: '/pricing', permanent: true },
      { source: '/fr/secteurs-dinnovation-strategique', destination: '/industries', permanent: true },
      { source: '/fr/secteurs-dinnovation-strategique/', destination: '/industries', permanent: true },
      { source: '/fr/blog', destination: '/blog', permanent: true },
      { source: '/fr/blog/', destination: '/blog', permanent: true },
      { source: '/fr/8move', destination: '/products', permanent: true },
      { source: '/fr/8move/', destination: '/products', permanent: true },
      { source: '/fr/iam-trade', destination: '/products/iam-trade', permanent: true },
      { source: '/fr/iam-trade/', destination: '/products/iam-trade', permanent: true },

      // ─── DE localized page redirects ──────────────────────────────────────
      { source: '/de/ueber-uns', destination: '/about', permanent: true },
      { source: '/de/ueber-uns/', destination: '/about', permanent: true },
      { source: '/de/unser-team', destination: '/team', permanent: true },
      { source: '/de/unser-team/', destination: '/team', permanent: true },
      { source: '/de/kontakte', destination: '/contact', permanent: true },
      { source: '/de/kontakte/', destination: '/contact', permanent: true },
      { source: '/de/unsere-dienstleistungen', destination: '/services', permanent: true },
      { source: '/de/unsere-dienstleistungen/', destination: '/services', permanent: true },
      { source: '/de/unsere-dienstleistungen/cloud-beratung', destination: '/services/cloud-consulting', permanent: true },
      { source: '/de/unsere-dienstleistungen/cloud-beratung/', destination: '/services/cloud-consulting', permanent: true },
      { source: '/de/unsere-dienstleistungen/embedded-und-iot', destination: '/services/embedded-and-iot', permanent: true },
      { source: '/de/unsere-dienstleistungen/embedded-und-iot/', destination: '/services/embedded-and-iot', permanent: true },
      { source: '/de/unsere-dienstleistungen/startups-cto-as-a-service', destination: '/services/cto-as-a-service', permanent: true },
      { source: '/de/unsere-dienstleistungen/startups-cto-as-a-service/', destination: '/services/cto-as-a-service', permanent: true },
      { source: '/de/unsere-dienstleistungen/softwaretechnik', destination: '/services/software-engineering', permanent: true },
      { source: '/de/unsere-dienstleistungen/softwaretechnik/', destination: '/services/software-engineering', permanent: true },
      { source: '/de/unsere-dienstleistungen/softwareentwicklung', destination: '/services/software-engineering', permanent: true },
      { source: '/de/unsere-dienstleistungen/softwareentwicklung/', destination: '/services/software-engineering', permanent: true },
      { source: '/de/ki-services', destination: '/services/ai-services', permanent: true },
      { source: '/de/ki-services/', destination: '/services/ai-services', permanent: true },
      { source: '/de/unsere-loesungen', destination: '/solutions', permanent: true },
      { source: '/de/unsere-loesungen/', destination: '/solutions', permanent: true },
      { source: '/de/unsere-loesungen/webseiten', destination: '/solutions/websites', permanent: true },
      { source: '/de/unsere-loesungen/webseiten/', destination: '/solutions/websites', permanent: true },
      { source: '/de/unsere-loesungen/webseiten/online-boutique', destination: '/solutions/websites/online-boutique', permanent: true },
      { source: '/de/unsere-loesungen/webseiten/online-boutique/', destination: '/solutions/websites/online-boutique', permanent: true },
      { source: '/de/unsere-loesungen/webseiten/web-broschure', destination: '/solutions/websites/web-brochure', permanent: true },
      { source: '/de/unsere-loesungen/webseiten/web-broschure/', destination: '/solutions/websites/web-brochure', permanent: true },
      { source: '/de/unsere-loesungen/webseiten/benutzerportal', destination: '/solutions/websites/user-portal', permanent: true },
      { source: '/de/unsere-loesungen/webseiten/benutzerportal/', destination: '/solutions/websites/user-portal', permanent: true },
      { source: '/de/unsere-loesungen/webseiten/kmu-website', destination: '/solutions/websites/sme-website', permanent: true },
      { source: '/de/unsere-loesungen/webseiten/kmu-website/', destination: '/solutions/websites/sme-website', permanent: true },
      { source: '/de/unsere-loesungen/e-commerce', destination: '/solutions/e-commerce', permanent: true },
      { source: '/de/unsere-loesungen/e-commerce/', destination: '/solutions/e-commerce', permanent: true },
      { source: '/de/site-preis', destination: '/pricing', permanent: true },
      { source: '/de/site-preis/', destination: '/pricing', permanent: true },
      { source: '/de/branchen-die-wir-innovieren', destination: '/industries', permanent: true },
      { source: '/de/branchen-die-wir-innovieren/', destination: '/industries', permanent: true },
      { source: '/de/blog', destination: '/blog', permanent: true },
      { source: '/de/blog/', destination: '/blog', permanent: true },
      { source: '/de/8move', destination: '/products', permanent: true },
      { source: '/de/8move/', destination: '/products', permanent: true },
      { source: '/de/iam-trade', destination: '/products/iam-trade', permanent: true },
      { source: '/de/iam-trade/', destination: '/products/iam-trade', permanent: true },

      // ─── IT localized page redirects ──────────────────────────────────────
      { source: '/it/chi-siamo', destination: '/about', permanent: true },
      { source: '/it/chi-siamo/', destination: '/about', permanent: true },
      { source: '/it/i-nostri-servizi', destination: '/services', permanent: true },
      { source: '/it/i-nostri-servizi/', destination: '/services', permanent: true },
      { source: '/it/i-nostri-servizi/consulenza-cloud', destination: '/services/cloud-consulting', permanent: true },
      { source: '/it/i-nostri-servizi/consulenza-cloud/', destination: '/services/cloud-consulting', permanent: true },
      { source: '/it/i-nostri-servizi/embedded-e-iot', destination: '/services/embedded-and-iot', permanent: true },
      { source: '/it/i-nostri-servizi/embedded-e-iot/', destination: '/services/embedded-and-iot', permanent: true },
      { source: '/it/i-nostri-servizi/startup-cto-as-a-service', destination: '/services/cto-as-a-service', permanent: true },
      { source: '/it/i-nostri-servizi/startup-cto-as-a-service/', destination: '/services/cto-as-a-service', permanent: true },
      { source: '/it/i-nostri-servizi/ingegneria-del-software', destination: '/services/software-engineering', permanent: true },
      { source: '/it/i-nostri-servizi/ingegneria-del-software/', destination: '/services/software-engineering', permanent: true },
      { source: '/it/i-nostri-servizi/sviluppo-software', destination: '/services/software-engineering', permanent: true },
      { source: '/it/i-nostri-servizi/sviluppo-software/', destination: '/services/software-engineering', permanent: true },
      { source: '/it/servizi-di-ia', destination: '/services/ai-services', permanent: true },
      { source: '/it/servizi-di-ia/', destination: '/services/ai-services', permanent: true },
      { source: '/it/le-nostre-soluzioni', destination: '/solutions', permanent: true },
      { source: '/it/le-nostre-soluzioni/', destination: '/solutions', permanent: true },
      { source: '/it/le-nostre-soluzioni/siti-web', destination: '/solutions/websites', permanent: true },
      { source: '/it/le-nostre-soluzioni/siti-web/', destination: '/solutions/websites', permanent: true },
      { source: '/it/le-nostre-soluzioni/siti-web/boutique-online', destination: '/solutions/websites/online-boutique', permanent: true },
      { source: '/it/le-nostre-soluzioni/siti-web/boutique-online/', destination: '/solutions/websites/online-boutique', permanent: true },
      { source: '/it/le-nostre-soluzioni/siti-web/brochure-web', destination: '/solutions/websites/web-brochure', permanent: true },
      { source: '/it/le-nostre-soluzioni/siti-web/brochure-web/', destination: '/solutions/websites/web-brochure', permanent: true },
      { source: '/it/le-nostre-soluzioni/siti-web/portale-utente', destination: '/solutions/websites/user-portal', permanent: true },
      { source: '/it/le-nostre-soluzioni/siti-web/portale-utente/', destination: '/solutions/websites/user-portal', permanent: true },
      { source: '/it/le-nostre-soluzioni/siti-web/sito-per-pmi', destination: '/solutions/websites/sme-website', permanent: true },
      { source: '/it/le-nostre-soluzioni/siti-web/sito-per-pmi/', destination: '/solutions/websites/sme-website', permanent: true },
      { source: '/it/le-nostre-soluzioni/e-commerce', destination: '/solutions/e-commerce', permanent: true },
      { source: '/it/le-nostre-soluzioni/e-commerce/', destination: '/solutions/e-commerce', permanent: true },
      { source: '/it/sito-prezzo', destination: '/pricing', permanent: true },
      { source: '/it/sito-prezzo/', destination: '/pricing', permanent: true },
      { source: '/it/settori-che-innoviamo', destination: '/industries', permanent: true },
      { source: '/it/settori-che-innoviamo/', destination: '/industries', permanent: true },
      { source: '/it/contatti', destination: '/contact', permanent: true },
      { source: '/it/contatti/', destination: '/contact', permanent: true },
      { source: '/it/blog', destination: '/blog', permanent: true },
      { source: '/it/blog/', destination: '/blog', permanent: true },
      { source: '/it/8move', destination: '/products', permanent: true },
      { source: '/it/8move/', destination: '/products', permanent: true },
      { source: '/it/iam-trade', destination: '/products/iam-trade', permanent: true },
      { source: '/it/iam-trade/', destination: '/products/iam-trade', permanent: true },

      // ─── FR blog post redirects (translated slug → /blog/en-slug) ─────────
      { source: '/fr/de-traditionnel-a-flexible-application-mobile-de-gestion-dentrepot', destination: '/blog/from-traditional-to-flexible-wms-mobile-app', permanent: true },
      { source: '/fr/de-traditionnel-a-flexible-application-mobile-de-gestion-dentrepot/', destination: '/blog/from-traditional-to-flexible-wms-mobile-app', permanent: true },
      { source: '/fr/publicite-gratuite-pour-les-restaurants-via-les-retours-clients', destination: '/blog/free-advertising-for-restaurants-through-customer-feedback', permanent: true },
      { source: '/fr/publicite-gratuite-pour-les-restaurants-via-les-retours-clients/', destination: '/blog/free-advertising-for-restaurants-through-customer-feedback', permanent: true },
      { source: '/fr/facilitez-vos-recherches-decouvrez-comment-iam-trade-simplifie-la-recherche-de-produits', destination: '/blog/simplifying-your-search-how-iam-trade-makes-finding-products-easy', permanent: true },
      { source: '/fr/facilitez-vos-recherches-decouvrez-comment-iam-trade-simplifie-la-recherche-de-produits/', destination: '/blog/simplifying-your-search-how-iam-trade-makes-finding-products-easy', permanent: true },
      { source: '/fr/stimuler-la-croissance-tactiques-essentielles-pour-votre-entreprise-ecommerce', destination: '/blog/driving-growth-essential-tactics-for-your-ecommerce-business', permanent: true },
      { source: '/fr/stimuler-la-croissance-tactiques-essentielles-pour-votre-entreprise-ecommerce/', destination: '/blog/driving-growth-essential-tactics-for-your-ecommerce-business', permanent: true },
      { source: '/fr/externalisation-liberer-lefficacite-et-linnovation-dans-les-projets-a-court-terme', destination: '/blog/the-power-of-outsourcing-unlocking-efficiency-and-innovation-in-short-term-projects', permanent: true },
      { source: '/fr/externalisation-liberer-lefficacite-et-linnovation-dans-les-projets-a-court-terme/', destination: '/blog/the-power-of-outsourcing-unlocking-efficiency-and-innovation-in-short-term-projects', permanent: true },
      { source: '/fr/nft-plateformes-dechange-en-jeu', destination: '/blog/nft-in-game-trading-platforms', permanent: true },
      { source: '/fr/nft-plateformes-dechange-en-jeu/', destination: '/blog/nft-in-game-trading-platforms', permanent: true },
      { source: '/fr/arenawave-logiciel-de-gestion-sportive', destination: '/blog/arenawave-digital-court-system', permanent: true },
      { source: '/fr/arenawave-logiciel-de-gestion-sportive/', destination: '/blog/arenawave-digital-court-system', permanent: true },
      { source: '/fr/iot-et-blockchain-sont-ils-vraiment-a-la-hauteur-des-attentes', destination: '/blog/iot-blockchain-can-it-truly-deliver', permanent: true },
      { source: '/fr/iot-et-blockchain-sont-ils-vraiment-a-la-hauteur-des-attentes/', destination: '/blog/iot-blockchain-can-it-truly-deliver', permanent: true },
      { source: '/fr/renforcer-les-petites-et-moyennes-entreprises-avec-des-solutions-de-securite-avancees', destination: '/blog/strengthening-small-and-medium-sized-businesses-through-advanced-security-solutions', permanent: true },
      { source: '/fr/renforcer-les-petites-et-moyennes-entreprises-avec-des-solutions-de-securite-avancees/', destination: '/blog/strengthening-small-and-medium-sized-businesses-through-advanced-security-solutions', permanent: true },
      { source: '/fr/securisez-votre-cloud-avec-un-budget-limite-un-guide-pour-les-pme', destination: '/blog/secure-your-cloud-on-a-budget-a-guide-for-smbs', permanent: true },
      { source: '/fr/securisez-votre-cloud-avec-un-budget-limite-un-guide-pour-les-pme/', destination: '/blog/secure-your-cloud-on-a-budget-a-guide-for-smbs', permanent: true },
      { source: '/fr/presentation-de-zenit-auto-notre-nouvelle-plateforme-de-pieces-automobiles-b2b', destination: '/blog/presenting-zenit-auto-our-new-b2b-auto-parts-platform', permanent: true },
      { source: '/fr/presentation-de-zenit-auto-notre-nouvelle-plateforme-de-pieces-automobiles-b2b/', destination: '/blog/presenting-zenit-auto-our-new-b2b-auto-parts-platform', permanent: true },
      { source: '/fr/le-kit-it-devolution-dentreprise-renforce-les-startups-retours-de-la-foire-du-valais-2024', destination: '/blog/trident-softwares-venture-evolution-it-package-empowers-startups-insights-from-foire-du-valais-2024', permanent: true },
      { source: '/fr/le-kit-it-devolution-dentreprise-renforce-les-startups-retours-de-la-foire-du-valais-2024/', destination: '/blog/trident-softwares-venture-evolution-it-package-empowers-startups-insights-from-foire-du-valais-2024', permanent: true },
      // FR-only posts → /blog/
      { source: '/fr/boutique-en-ligne-de-la-pochette-decouvrez-des-accessoires-raffines', destination: '/blog', permanent: true },
      { source: '/fr/boutique-en-ligne-de-la-pochette-decouvrez-des-accessoires-raffines/', destination: '/blog', permanent: true },
      { source: '/fr/rejoindre-le-cloud-resume-de-levenement', destination: '/blog', permanent: true },
      { source: '/fr/rejoindre-le-cloud-resume-de-levenement/', destination: '/blog', permanent: true },
      { source: '/fr/augmentez-vos-ventes-contenu-video-professionnel-pour-votre-boutique-en-ligne', destination: '/blog', permanent: true },
      { source: '/fr/augmentez-vos-ventes-contenu-video-professionnel-pour-votre-boutique-en-ligne/', destination: '/blog', permanent: true },
      { source: '/fr/notre-partenariat-avec-amazon-web-services-aws', destination: '/blog', permanent: true },
      { source: '/fr/notre-partenariat-avec-amazon-web-services-aws/', destination: '/blog', permanent: true },
      { source: '/fr/la-gestion-des-stocks-revolutionnaire', destination: '/blog', permanent: true },
      { source: '/fr/la-gestion-des-stocks-revolutionnaire/', destination: '/blog', permanent: true },
      { source: '/fr/lancement-du-site-web-de-lecole-de-langues-ardevaz', destination: '/blog', permanent: true },
      { source: '/fr/lancement-du-site-web-de-lecole-de-langues-ardevaz/', destination: '/blog', permanent: true },
      { source: '/fr/flutter-application-pour-personnel-dentrepot', destination: '/blog', permanent: true },
      { source: '/fr/flutter-application-pour-personnel-dentrepot/', destination: '/blog', permanent: true },
      { source: '/fr/adhesion-a-la-chambre-de-commerce-et-dindustrie-du-valais', destination: '/blog', permanent: true },
      { source: '/fr/adhesion-a-la-chambre-de-commerce-et-dindustrie-du-valais/', destination: '/blog', permanent: true },
      { source: '/fr/optimisation-defficacite-et-reduction-des-couts-avec-aws-lambda', destination: '/blog', permanent: true },
      { source: '/fr/optimisation-defficacite-et-reduction-des-couts-avec-aws-lambda/', destination: '/blog', permanent: true },
      { source: '/fr/iam-trade-plateforme-e-commerce-pour-les-detaillants-de-pneus-en-ligne', destination: '/blog', permanent: true },
      { source: '/fr/iam-trade-plateforme-e-commerce-pour-les-detaillants-de-pneus-en-ligne/', destination: '/blog', permanent: true },
      { source: '/fr/pleins-feux-sur-les-bracelets-transformez-votre-magasin-de-montres-avec-des-descriptions-captivantes', destination: '/blog', permanent: true },
      { source: '/fr/pleins-feux-sur-les-bracelets-transformez-votre-magasin-de-montres-avec-des-descriptions-captivantes/', destination: '/blog', permanent: true },
      { source: '/fr/lancement-du-site-web-du-club-expat-go-valais', destination: '/blog', permanent: true },
      { source: '/fr/lancement-du-site-web-du-club-expat-go-valais/', destination: '/blog', permanent: true },
      { source: '/fr/le-bot-vocal-ia-ameliore-le-service-client', destination: '/blog', permanent: true },
      { source: '/fr/le-bot-vocal-ia-ameliore-le-service-client/', destination: '/blog', permanent: true },
      { source: '/fr/de-manuel-a-automatique-description-fiche-produit-alimentee-par-lia', destination: '/blog', permanent: true },
      { source: '/fr/de-manuel-a-automatique-description-fiche-produit-alimentee-par-lia/', destination: '/blog', permanent: true },
      { source: '/fr/presentation-de-notre-nouveau-panneau-dadministration-b2b-client', destination: '/blog', permanent: true },
      { source: '/fr/presentation-de-notre-nouveau-panneau-dadministration-b2b-client/', destination: '/blog', permanent: true },
      { source: '/fr/comment-automatiser-votre-service-de-courrier-avec-integration-erp', destination: '/blog', permanent: true },
      { source: '/fr/comment-automatiser-votre-service-de-courrier-avec-integration-erp/', destination: '/blog', permanent: true },
      { source: '/fr/tarification-dynamique-aws-via-un-microservice-dans-un-projet-de-vente-de-pieces-automobiles', destination: '/blog', permanent: true },
      { source: '/fr/tarification-dynamique-aws-via-un-microservice-dans-un-projet-de-vente-de-pieces-automobiles/', destination: '/blog', permanent: true },
      { source: '/fr/comment-les-systemes-de-suivi-des-envois-stimulent-les-ventes-en-ligne', destination: '/blog', permanent: true },
      { source: '/fr/comment-les-systemes-de-suivi-des-envois-stimulent-les-ventes-en-ligne/', destination: '/blog', permanent: true },
      { source: '/fr/optimiser-les-autorisations-des-utilisateurs-aws-strategie-pour-les-entreprises-en-croissance', destination: '/blog', permanent: true },
      { source: '/fr/optimiser-les-autorisations-des-utilisateurs-aws-strategie-pour-les-entreprises-en-croissance/', destination: '/blog', permanent: true },
      { source: '/fr/exploration-du-paiement-en-ligne-pour-e-commerce-types-securite-et-conseils', destination: '/blog', permanent: true },
      { source: '/fr/exploration-du-paiement-en-ligne-pour-e-commerce-types-securite-et-conseils/', destination: '/blog', permanent: true },
      { source: '/fr/lancement-du-site-web-mastertool-boutique-doutils-en-ligne-en-slovaquie', destination: '/blog', permanent: true },
      { source: '/fr/lancement-du-site-web-mastertool-boutique-doutils-en-ligne-en-slovaquie/', destination: '/blog', permanent: true },
      { source: '/fr/augmenter-les-ventes-meilleures-pratiques-et-strategies-de-prix', destination: '/blog', permanent: true },
      { source: '/fr/augmenter-les-ventes-meilleures-pratiques-et-strategies-de-prix/', destination: '/blog', permanent: true },
      { source: '/fr/la-pochettes-internetshop-entdecken-sie-stilvolle-accessoires', destination: '/blog', permanent: true },
      { source: '/fr/la-pochettes-internetshop-entdecken-sie-stilvolle-accessoires/', destination: '/blog', permanent: true },

      // ─── DE blog post redirects ────────────────────────────────────────────
      { source: '/de/von-traditionell-zu-flexibel-wms-mobile-app', destination: '/blog/from-traditional-to-flexible-wms-mobile-app', permanent: true },
      { source: '/de/von-traditionell-zu-flexibel-wms-mobile-app/', destination: '/blog/from-traditional-to-flexible-wms-mobile-app', permanent: true },
      { source: '/de/kostenlose-werbung-fuer-restaurants-durch-kundenfeedback', destination: '/blog/free-advertising-for-restaurants-through-customer-feedback', permanent: true },
      { source: '/de/kostenlose-werbung-fuer-restaurants-durch-kundenfeedback/', destination: '/blog/free-advertising-for-restaurants-through-customer-feedback', permanent: true },
      { source: '/de/vereinfachen-sie-ihre-suche-wie-iam-trade-das-finden-von-produkten-erleichtert', destination: '/blog/simplifying-your-search-how-iam-trade-makes-finding-products-easy', permanent: true },
      { source: '/de/vereinfachen-sie-ihre-suche-wie-iam-trade-das-finden-von-produkten-erleichtert/', destination: '/blog/simplifying-your-search-how-iam-trade-makes-finding-products-easy', permanent: true },
      { source: '/de/wachstum-vorantreiben-wesentliche-taktiken-fur-ihr-ecommerce-unternehmen', destination: '/blog/driving-growth-essential-tactics-for-your-ecommerce-business', permanent: true },
      { source: '/de/wachstum-vorantreiben-wesentliche-taktiken-fur-ihr-ecommerce-unternehmen/', destination: '/blog/driving-growth-essential-tactics-for-your-ecommerce-business', permanent: true },
      { source: '/de/die-kraft-des-outsourcings-effizienz-und-innovation-in-kurzfristigen-projekten-freisetzen', destination: '/blog/the-power-of-outsourcing-unlocking-efficiency-and-innovation-in-short-term-projects', permanent: true },
      { source: '/de/die-kraft-des-outsourcings-effizienz-und-innovation-in-kurzfristigen-projekten-freisetzen/', destination: '/blog/the-power-of-outsourcing-unlocking-efficiency-and-innovation-in-short-term-projects', permanent: true },
      { source: '/de/arenawave-sportmanagement-software', destination: '/blog/arenawave-digital-court-system', permanent: true },
      { source: '/de/arenawave-sportmanagement-software/', destination: '/blog/arenawave-digital-court-system', permanent: true },
      { source: '/de/starkung-kleiner-und-mittelstandischer-unternehmen-durch-fortschrittliche-sicherheitslosungen', destination: '/blog/strengthening-small-and-medium-sized-businesses-through-advanced-security-solutions', permanent: true },
      { source: '/de/starkung-kleiner-und-mittelstandischer-unternehmen-durch-fortschrittliche-sicherheitslosungen/', destination: '/blog/strengthening-small-and-medium-sized-businesses-through-advanced-security-solutions', permanent: true },
      { source: '/de/sichern-sie-ihre-cloud-im-rahmen-eines-budgets-ein-leitfaden-fuer-kmus', destination: '/blog/secure-your-cloud-on-a-budget-a-guide-for-smbs', permanent: true },
      { source: '/de/sichern-sie-ihre-cloud-im-rahmen-eines-budgets-ein-leitfaden-fuer-kmus/', destination: '/blog/secure-your-cloud-on-a-budget-a-guide-for-smbs', permanent: true },
      { source: '/de/vorstellung-von-zenit-auto-unsere-neue-b2b-autoteileplattform', destination: '/blog/presenting-zenit-auto-our-new-b2b-auto-parts-platform', permanent: true },
      { source: '/de/vorstellung-von-zenit-auto-unsere-neue-b2b-autoteileplattform/', destination: '/blog/presenting-zenit-auto-our-new-b2b-auto-parts-platform', permanent: true },
      { source: '/de/das-venture-evolution-it-paket-staerkt-startups-einblicke-von-der-foire-du-valais-2024', destination: '/blog/trident-softwares-venture-evolution-it-package-empowers-startups-insights-from-foire-du-valais-2024', permanent: true },
      { source: '/de/das-venture-evolution-it-paket-staerkt-startups-einblicke-von-der-foire-du-valais-2024/', destination: '/blog/trident-softwares-venture-evolution-it-package-empowers-startups-insights-from-foire-du-valais-2024', permanent: true },
      // DE-only posts → /blog/
      { source: '/de/la-pochettes-internetshop-entdecken-sie-stilvolle-accessoires', destination: '/blog', permanent: true },
      { source: '/de/la-pochettes-internetshop-entdecken-sie-stilvolle-accessoires/', destination: '/blog', permanent: true },
      { source: '/de/zusammenfassung-des-treten-sie-der-cloud-bei-events', destination: '/blog', permanent: true },
      { source: '/de/zusammenfassung-des-treten-sie-der-cloud-bei-events/', destination: '/blog', permanent: true },
      { source: '/de/verkaeufe-steigern-professionelle-videoinhalte-fuer-ihr-online-geschaeft', destination: '/blog', permanent: true },
      { source: '/de/verkaeufe-steigern-professionelle-videoinhalte-fuer-ihr-online-geschaeft/', destination: '/blog', permanent: true },
      { source: '/de/unsere-partnerschaft-mit-aws-web-services-amazon', destination: '/blog', permanent: true },
      { source: '/de/unsere-partnerschaft-mit-aws-web-services-amazon/', destination: '/blog', permanent: true },
      { source: '/de/revolutionaere-veraenderungen-in-der-lagerverwaltung', destination: '/blog', permanent: true },
      { source: '/de/revolutionaere-veraenderungen-in-der-lagerverwaltung/', destination: '/blog', permanent: true },
      { source: '/de/ardevaz-sprachschule-website-launch', destination: '/blog', permanent: true },
      { source: '/de/ardevaz-sprachschule-website-launch/', destination: '/blog', permanent: true },
      { source: '/de/flutter-app-flutter-app-fuer-und-lagerhalter', destination: '/blog', permanent: true },
      { source: '/de/flutter-app-flutter-app-fuer-und-lagerhalter/', destination: '/blog', permanent: true },
      { source: '/de/mitgliedschaft-in-der-handelskammer-und-industrie-des-kantons-wallis', destination: '/blog', permanent: true },
      { source: '/de/mitgliedschaft-in-der-handelskammer-und-industrie-des-kantons-wallis/', destination: '/blog', permanent: true },
      { source: '/de/maximierung-von-effizienz-und-kosteneinsparungen-mit-lambda-aws', destination: '/blog', permanent: true },
      { source: '/de/maximierung-von-effizienz-und-kosteneinsparungen-mit-lambda-aws/', destination: '/blog', permanent: true },
      { source: '/de/iam-trade-e-commerce-plattform-fuer-online-reifenhaendler', destination: '/blog', permanent: true },
      { source: '/de/iam-trade-e-commerce-plattform-fuer-online-reifenhaendler/', destination: '/blog', permanent: true },
      { source: '/de/band-spotlight-verwandeln-sie-ihr-uhrengeschaeft-mit-ansprechenden-beschreibungen', destination: '/blog', permanent: true },
      { source: '/de/band-spotlight-verwandeln-sie-ihr-uhrengeschaeft-mit-ansprechenden-beschreibungen/', destination: '/blog', permanent: true },
      { source: '/de/go-wallis-expat-club-website-starten', destination: '/blog', permanent: true },
      { source: '/de/go-wallis-expat-club-website-starten/', destination: '/blog', permanent: true },
      { source: '/de/ki-voicebot-optimiert-den-kundenservice', destination: '/blog', permanent: true },
      { source: '/de/ki-voicebot-optimiert-den-kundenservice/', destination: '/blog', permanent: true },
      { source: '/de/von-manuell-zu-automatisch-ki-gesteuerte-produktbeschreibung', destination: '/blog', permanent: true },
      { source: '/de/von-manuell-zu-automatisch-ki-gesteuerte-produktbeschreibung/', destination: '/blog', permanent: true },
      { source: '/de/vorstellung-unseres-neuen-b2b-admin-panel', destination: '/blog', permanent: true },
      { source: '/de/vorstellung-unseres-neuen-b2b-admin-panel/', destination: '/blog', permanent: true },
      { source: '/de/wie-sie-ihren-kurierdienst-mit-erp-integration-automatisieren-konnen', destination: '/blog', permanent: true },
      { source: '/de/wie-sie-ihren-kurierdienst-mit-erp-integration-automatisieren-konnen/', destination: '/blog', permanent: true },
      { source: '/de/online-shop-zahlungen-erkunden-typen-sicherheit-und-tipps', destination: '/blog', permanent: true },
      { source: '/de/online-shop-zahlungen-erkunden-typen-sicherheit-und-tipps/', destination: '/blog', permanent: true },
      { source: '/de/auf-erfolgskurs-wie-sendungsverfolgungssysteme-den-e-commerce-umsatz-steigern', destination: '/blog', permanent: true },
      { source: '/de/auf-erfolgskurs-wie-sendungsverfolgungssysteme-den-e-commerce-umsatz-steigern/', destination: '/blog', permanent: true },
      { source: '/de/dynamische-preisgestaltung-auf-aws-durch-einen-microservice-in-einem-projekt-fur-den-verkauf-von-autoteilen', destination: '/blog', permanent: true },
      { source: '/de/dynamische-preisgestaltung-auf-aws-durch-einen-microservice-in-einem-projekt-fur-den-verkauf-von-autoteilen/', destination: '/blog', permanent: true },
      { source: '/de/vereinfachung-der-aws-benutzerberechtigungen-eine-strategie-fuer-wachsende-unternehmen', destination: '/blog', permanent: true },
      { source: '/de/vereinfachung-der-aws-benutzerberechtigungen-eine-strategie-fuer-wachsende-unternehmen/', destination: '/blog', permanent: true },
      { source: '/de/umsatzmaximierung-tipps-zur-erstellung-uberzeugender-produktseiten-fur-ihren-online-reifenshop', destination: '/blog', permanent: true },
      { source: '/de/umsatzmaximierung-tipps-zur-erstellung-uberzeugender-produktseiten-fur-ihren-online-reifenshop/', destination: '/blog', permanent: true },
      { source: '/de/verkauf-von-gebrauchten-reifen-online-wesentliche-tipps', destination: '/blog', permanent: true },
      { source: '/de/verkauf-von-gebrauchten-reifen-online-wesentliche-tipps/', destination: '/blog', permanent: true },
      { source: '/de/mastertool-website-start-online-werkzeugladen-in-der-slowakei', destination: '/blog', permanent: true },
      { source: '/de/mastertool-website-start-online-werkzeugladen-in-der-slowakei/', destination: '/blog', permanent: true },

      // ─── IT blog post redirects ────────────────────────────────────────────
      { source: '/it/da-tradizionale-a-flessibile-app-mobile-wms', destination: '/blog/from-traditional-to-flexible-wms-mobile-app', permanent: true },
      { source: '/it/da-tradizionale-a-flessibile-app-mobile-wms/', destination: '/blog/from-traditional-to-flexible-wms-mobile-app', permanent: true },
      { source: '/it/pubblicita-gratis-per-ristoranti-tramite-il-feedback-dei-clienti', destination: '/blog/free-advertising-for-restaurants-through-customer-feedback', permanent: true },
      { source: '/it/pubblicita-gratis-per-ristoranti-tramite-il-feedback-dei-clienti/', destination: '/blog/free-advertising-for-restaurants-through-customer-feedback', permanent: true },
      { source: '/it/semplificare-la-tua-ricerca-come-iam-trade-rende-facile-trovare-prodotti', destination: '/blog/simplifying-your-search-how-iam-trade-makes-finding-products-easy', permanent: true },
      { source: '/it/semplificare-la-tua-ricerca-come-iam-trade-rende-facile-trovare-prodotti/', destination: '/blog/simplifying-your-search-how-iam-trade-makes-finding-products-easy', permanent: true },
      { source: '/it/guidare-la-crescita-tattiche-essenziali-per-il-tuo-business-ecommerce', destination: '/blog/driving-growth-essential-tactics-for-your-ecommerce-business', permanent: true },
      { source: '/it/guidare-la-crescita-tattiche-essenziali-per-il-tuo-business-ecommerce/', destination: '/blog/driving-growth-essential-tactics-for-your-ecommerce-business', permanent: true },
      { source: '/it/il-potere-dellesternalizzazione-sbloccare-lefficienza-e-linnovazione-nei-progetti-a-breve-termine', destination: '/blog/the-power-of-outsourcing-unlocking-efficiency-and-innovation-in-short-term-projects', permanent: true },
      { source: '/it/il-potere-dellesternalizzazione-sbloccare-lefficienza-e-linnovazione-nei-progetti-a-breve-termine/', destination: '/blog/the-power-of-outsourcing-unlocking-efficiency-and-innovation-in-short-term-projects', permanent: true },
      { source: '/it/arenawave-software-di-gestione-sportiva', destination: '/blog/arenawave-digital-court-system', permanent: true },
      { source: '/it/arenawave-software-di-gestione-sportiva/', destination: '/blog/arenawave-digital-court-system', permanent: true },
      { source: '/it/rafforzare-le-piccole-e-medie-imprese-attraverso-soluzioni-di-sicurezza-avanzate', destination: '/blog/strengthening-small-and-medium-sized-businesses-through-advanced-security-solutions', permanent: true },
      { source: '/it/rafforzare-le-piccole-e-medie-imprese-attraverso-soluzioni-di-sicurezza-avanzate/', destination: '/blog/strengthening-small-and-medium-sized-businesses-through-advanced-security-solutions', permanent: true },
      { source: '/it/proteggi-la-tua-cloud-con-un-budget-limitato-una-guida-per-le-pmi', destination: '/blog/secure-your-cloud-on-a-budget-a-guide-for-smbs', permanent: true },
      { source: '/it/proteggi-la-tua-cloud-con-un-budget-limitato-una-guida-per-le-pmi/', destination: '/blog/secure-your-cloud-on-a-budget-a-guide-for-smbs', permanent: true },
      { source: '/it/presentazione-di-zenit-auto-nostra-nuova-piattaforma-b2b-per-pezzi-di-ricambio-auto', destination: '/blog/presenting-zenit-auto-our-new-b2b-auto-parts-platform', permanent: true },
      { source: '/it/presentazione-di-zenit-auto-nostra-nuova-piattaforma-b2b-per-pezzi-di-ricambio-auto/', destination: '/blog/presenting-zenit-auto-our-new-b2b-auto-parts-platform', permanent: true },
      { source: '/it/il-pacchetto-it-di-evoluzione-delle-venture-potenzia-le-startup-approfondimenti-dalla-foire-du-valais-2024', destination: '/blog/trident-softwares-venture-evolution-it-package-empowers-startups-insights-from-foire-du-valais-2024', permanent: true },
      { source: '/it/il-pacchetto-it-di-evoluzione-delle-venture-potenzia-le-startup-approfondimenti-dalla-foire-du-valais-2024/', destination: '/blog/trident-softwares-venture-evolution-it-package-empowers-startups-insights-from-foire-du-valais-2024', permanent: true },
      // IT-only posts → /blog/
      { source: '/it/shop-online-la-pochette-scopri-gli-accessori-di-stile', destination: '/blog', permanent: true },
      { source: '/it/shop-online-la-pochette-scopri-gli-accessori-di-stile/', destination: '/blog', permanent: true },
      { source: '/it/riepilogo-dellevento-unisciti-al-cloud', destination: '/blog', permanent: true },
      { source: '/it/riepilogo-dellevento-unisciti-al-cloud/', destination: '/blog', permanent: true },
      { source: '/it/aumentare-le-vendite-contenuti-video-professionali-per-il-vostro-negozio-online', destination: '/blog', permanent: true },
      { source: '/it/aumentare-le-vendite-contenuti-video-professionali-per-il-vostro-negozio-online/', destination: '/blog', permanent: true },
      { source: '/it/la-nostra-partnership-con-web-services-amazon-aws', destination: '/blog', permanent: true },
      { source: '/it/la-nostra-partnership-con-web-services-amazon-aws/', destination: '/blog', permanent: true },
      { source: '/it/rivoluzionare-la-gestione-inventario', destination: '/blog', permanent: true },
      { source: '/it/rivoluzionare-la-gestione-inventario/', destination: '/blog', permanent: true },
      { source: '/it/lancio-di-un-sito-web-scolastico-della-scuola-ardevaz', destination: '/blog', permanent: true },
      { source: '/it/lancio-di-un-sito-web-scolastico-della-scuola-ardevaz/', destination: '/blog', permanent: true },
      { source: '/it/applicazione-basata-sul-flutter', destination: '/blog', permanent: true },
      { source: '/it/applicazione-basata-sul-flutter/', destination: '/blog', permanent: true },
      { source: '/it/membri-della-camera-di-commercio-e-industria-del-vallese', destination: '/blog', permanent: true },
      { source: '/it/membri-della-camera-di-commercio-e-industria-del-vallese/', destination: '/blog', permanent: true },
      { source: '/it/massimizzazione-di-efficienza-e-risparmio-di-costi-con-amazon-web-services-lambda', destination: '/blog', permanent: true },
      { source: '/it/massimizzazione-di-efficienza-e-risparmio-di-costi-con-amazon-web-services-lambda/', destination: '/blog', permanent: true },
      { source: '/it/iam-trade-piattaforma-di-e-commerce-per-rivenditori-di-pneumatici-online', destination: '/blog', permanent: true },
      { source: '/it/iam-trade-piattaforma-di-e-commerce-per-rivenditori-di-pneumatici-online/', destination: '/blog', permanent: true },
      { source: '/it/cinturino-in-evidenza-trasformate-il-vostro-negozio-di-orologi-con-descrizioni-vivaci', destination: '/blog', permanent: true },
      { source: '/it/cinturino-in-evidenza-trasformate-il-vostro-negozio-di-orologi-con-descrizioni-vivaci/', destination: '/blog', permanent: true },
      { source: '/it/lancio-del-sito-web-del-club-degli-espatriati-go-valais', destination: '/blog', permanent: true },
      { source: '/it/lancio-del-sito-web-del-club-degli-espatriati-go-valais/', destination: '/blog', permanent: true },
      { source: '/it/bot-voce-ia-migliorano-il-servizio-clienti', destination: '/blog', permanent: true },
      { source: '/it/bot-voce-ia-migliorano-il-servizio-clienti/', destination: '/blog', permanent: true },
      { source: '/it/dal-manuale-allautomatico-descrizione-prodotto-alimentata-dallia', destination: '/blog', permanent: true },
      { source: '/it/dal-manuale-allautomatico-descrizione-prodotto-alimentata-dallia/', destination: '/blog', permanent: true },
      { source: '/it/presentazione-del-nostro-nuovo-di-amministrazione-b2b-clienti', destination: '/blog', permanent: true },
      { source: '/it/presentazione-del-nostro-nuovo-di-amministrazione-b2b-clienti/', destination: '/blog', permanent: true },
      { source: '/it/come-automatizzare-il-servizio-di-corriere-con-lintegrazione-erp', destination: '/blog', permanent: true },
      { source: '/it/come-automatizzare-il-servizio-di-corriere-con-lintegrazione-erp/', destination: '/blog', permanent: true },
      { source: '/it/esplorare-i-pagamenti-online-tipologie-sicurezza-e-consigli-per-i-negozi', destination: '/blog', permanent: true },
      { source: '/it/esplorare-i-pagamenti-online-tipologie-sicurezza-e-consigli-per-i-negozi/', destination: '/blog', permanent: true },
      { source: '/it/come-i-sistemi-di-tracking-spedizione-potenziano-le-vendite-online', destination: '/blog', permanent: true },
      { source: '/it/come-i-sistemi-di-tracking-spedizione-potenziano-le-vendite-online/', destination: '/blog', permanent: true },
      { source: '/it/prezzo-dinamico-aws-tramite-un-microservizio-in-un-progetto-di-vendita-di-ricambi-automobilistici', destination: '/blog', permanent: true },
      { source: '/it/prezzo-dinamico-aws-tramite-un-microservizio-in-un-progetto-di-vendita-di-ricambi-automobilistici/', destination: '/blog', permanent: true },
      { source: '/it/ottimizzazione-delle-autorizzazioni-utente-aws-una-strategia-per-le-aziende-in-crescita', destination: '/blog', permanent: true },
      { source: '/it/ottimizzazione-delle-autorizzazioni-utente-aws-una-strategia-per-le-aziende-in-crescita/', destination: '/blog', permanent: true },
      { source: '/it/massimizzare-le-vendite-consigli-per-creare-pagine-prodotto-convincenti-per-il-tuo-negozio-di-pneumatici-online', destination: '/blog', permanent: true },
      { source: '/it/massimizzare-le-vendite-consigli-per-creare-pagine-prodotto-convincenti-per-il-tuo-negozio-di-pneumatici-online/', destination: '/blog', permanent: true },
      { source: '/it/vendita-di-gomme-usate-online-consigli-essenziali', destination: '/blog', permanent: true },
      { source: '/it/vendita-di-gomme-usate-online-consigli-essenziali/', destination: '/blog', permanent: true },
      { source: '/it/lancio-del-sito-web-mastertool-negozio-di-utensili-online-in-slovacchia', destination: '/blog', permanent: true },
      { source: '/it/lancio-del-sito-web-mastertool-negozio-di-utensili-online-in-slovacchia/', destination: '/blog', permanent: true },
    ]
  },

  async rewrites() {
    return {
      beforeFiles: [
        { source: '/:locale(en|de|fr|it)/:path*', destination: '/:path*' },
        { source: '/:locale(en|de|fr|it)', destination: '/' },
      ],
    }
  },

  async headers() {
    const csp = [
      "default-src 'self'",
      "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com",
      "style-src 'self' 'unsafe-inline'",
      "font-src 'self' data:",
      "img-src 'self' data: blob: https: https://www.google-analytics.com",
      "connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://www.googletagmanager.com https://*.linkedin.com https://px.ads.linkedin.com",
      "frame-src 'self' https://www.youtube.com https://www.google.com",
    ].join('; ')

    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
          { key: 'Strict-Transport-Security', value: 'max-age=31536000; includeSubDomains' },
          { key: 'Content-Security-Policy', value: csp },
        ],
      },
    ]
  },

  webpack: (webpackConfig) => {
    webpackConfig.resolve.extensionAlias = {
      '.cjs': ['.cts', '.cjs'],
      '.js': ['.ts', '.tsx', '.js', '.jsx'],
      '.mjs': ['.mts', '.mjs'],
    }
    return webpackConfig
  },
}

export default isCloudflare
  ? withNextIntl(nextConfig)
  : withPayload(withNextIntl(nextConfig), { devBundleServerPackages: false })
